### ISSUE TITLE
Discogs import to MB: issue regarding titles spanning multiple tracks

### ISSUE THREAD

**Issue by totalwormage** [murdos/musicbrainz-userscripts#117]
There's a problem importing albums that have titles comprised of multiple parts. Discogs steps away from their normal track listing and uses a header for all tracks under the same title. See for instance tracks 11 to 13 on this release: https://www.discogs.com/Steve-Vai-Modern-Primitive-Passion-And-Warfare/release/8691107

These tracks are getting imported as "part I", "part II" etc. without their actual title listed.

I'm not a user of this script, just noticed this while tagging said release. :]

**Comment by zas** [comment]
I think there is nothign much to do here, if we concatenate section title and track's title it would work for "Pink And Blows Over: " + "Part I", but it would fail for last track "Bonus Tracks" + "Lovely Elixir"
I guess fixing it by hand while importing isn't much an issue, importers aren't meant to be perfect 1:1 because sources aren't always consistent, and often don't match the MB's way.

**Comment by totalwormage** [comment]
hmm, well there is a colon at the end of the header for multiple tracks with the same title and none at the end of other matching headers on discogs. don't know how consistent they are with that though.

& indeed, not a lot of work to fix by hand, just something users should be aware of, just a heads up ^_^
