### ISSUE TITLE
Wrong artist on Bandcamp import

### ISSUE THREAD

**Issue by liftarn** [murdos/musicbrainz-userscripts#118]
When importing http://herbloodinmyveins.bandcamp.com/album/essentianephe the artist is set as _Her blood in my veins_ rather than _aynth_ as expected.

**Comment by zas** [comment]
I just tested, and artist field is set to "aynth" as shown on following screenshot:

![capture du 2016-08-04 11-26-28](https://cloud.githubusercontent.com/assets/151042/17397019/7864affa-5a36-11e6-9f5a-2c53bdfb0ec3.png)

What is your browser ?

**Comment by liftarn** [comment]
Just tested and now it works for me.

**Comment by jesus2099** [comment]
Please reopen this issue.
It’s strange https://musicbrainz.org/edit/59102387#note-59102387-3

I tried it a few days ago https://musicbrainz.org/edit/58987903 → https://perfectaesthetics.bandcamp.com/album/invasion-of-grenada → import with correct artist **Milij Pritula**.

But today I try it same https://perfectaesthetics.bandcamp.com/album/invasion-of-grenada → import with incorrect artist **Sobranie 8 18** like the original editor.

Why this artist? It seems completely unrelated!?

**Comment by roman412** [comment]
I can confirm this. 
I didn't perform an investigation of this, but I think I have an idea. Sometimes on the bandcamp album page there's an arrow back to the label or other artist. It is placed in the top left corner (here):

![untitled](https://user-images.githubusercontent.com/2878904/52170240-dd4d9d00-2757-11e9-968d-809491e3722b.png)

I don't know what causes this arrow to appear (this is bancamp business logic), but sometimes I could see a bandcamp icon on it. In this case, if I click on the icon it will lead to _Sobranie 18_ album.
But the arrow is missing now, however I still can reproduce this bug when importing above-mentioned album.

So, very likely that the Musicbrainz link value at this page was cached, and the cache is wrong now. I don't know where murdos scripts are storing its cache, so I just open incognito window to skip the cache. And the bug is not reproducing in incognito.

I apologize for my messy message, but I don't have time to do analysis now.

**Comment by zas** [comment]
> Please reopen this issue.
> It’s strange https://musicbrainz.org/edit/59102387#note-59102387-3
> 
> I tried it a few days ago https://musicbrainz.org/edit/58987903 → https://perfectaesthetics.bandcamp.com/album/invasion-of-grenada → import with correct artist **Milij Pritula**.
> 
> But today I try it same https://perfectaesthetics.bandcamp.com/album/invasion-of-grenada → import with incorrect artist **Sobranie 8 18** like the original editor.
> 
> Why this artist? It seems completely unrelated!?

Because https://musicbrainz.org/artist/cf0a3e91-c806-4c34-8b53-f52fa8edc00c has https://perfectaesthetics.bandcamp.com/ as Bandcamp relationships.

Fixed in https://musicbrainz.org/edit/59141299

**Comment by zas** [comment]
> So, very likely that the Musicbrainz link value at this page was cached, and the cache is wrong now. I don't know where murdos scripts are storing its cache, so I just open incognito window to skip the cache. And the bug is not reproducing in incognito.

Cached values are stored in a Local Storage named BCI_MBLINKS_CACHE-v2
