### ISSUE TITLE
Import not appearing for some Discogs releases (box sets?)

### ISSUE THREAD

**Issue by iceequal** [murdos/musicbrainz-userscripts#13]
I can get other releases to load - just not for this release:

http://www.discogs.com/release/5505076

As per title, I wonder if it is because it is a box set. Tried using both Chrome (Tampermonkey) and Safari (ninjakit).

![screen shot 2014-04-09 at 12 53 01 pm](https://cloud.githubusercontent.com/assets/3310369/2651615/37e38a6e-bf92-11e3-9b63-d9b21f87b835.png)

**Comment by awesomer** [comment]
All 4 of the releases in the previous comment now show an import button, for the record.

I have two releases where a button never shows. I'm in Chrome OSX + Tampermonkey and see buttons on almost all releases.

http://www.discogs.com/Various-When-We-Were-Things-Part-1/release/73531
http://www.discogs.com/Joy-Orbison-Boddika-Trickys-Team/release/5609148

Let me know if it's appropriate for me to add any other releases with this problem to this ticket.

**Comment by zas** [comment]
The issue with http://www.discogs.com/Joy-Orbison-Boddika-Trickys-Team/release/5609148 is that the buttons aren't shown because script failed to insert them due to the lack of the usual social section, it isn't a particular issue with the release itself.
Fixed by https://github.com/murdos/musicbrainz-userscripts/commit/30be1ef96419d107264f11125088899e427e37cf

The http://www.discogs.com/Various-When-We-Were-Things-Part-1/release/73531 issue was fixed too by a previous commit: https://github.com/murdos/musicbrainz-userscripts/commit/1bf80fbaf918e12028d89e1f3801298f63e65977

Please create one issue per problematic link, it will ease things ;)

**Comment by murdos** [comment]
Original issue partially fixed with 9b8a8ef5c42d6d1426be3235f3337c323d40efc6

As correctly explained by @96187 there are 2 issues : 
1. the first one is that we were trying to tread "Box-set" as a medium format <= issue fixed with the commit
2. the second one is that release reuses A1 track number for the 2nd medium <= this is not handled by the import script, my position is that discogs data should be fixed instead.
