### ISSUE TITLE
Add support for Discogs compositions

### ISSUE THREAD

**Issue by CyberSkull** [murdos/musicbrainz-userscripts#201]
Discogs now has compositions (works, in beta as of this post). MusicBrainz works now support linking to the cleaned Discogs compositon URLs. It would be great if the Discogs importer could show compositions linked to MB works.

Example:
https://musicbrainz.org/work/de961928-df62-4547-aa2c-e0642d5967e7 has the link to https://www.discogs.com/composition/7daf9e08-cd47-456d-9714-88fed394d0f1

I'm looking forward to seeing some little yellow boxes with the letter "W" in them. ;)

**Comment by awesomer** [comment]
Unfortunately, Discogs no longer has compositions. The beta failed, apparently, due to performance reasons.

https://www.discogs.com/forum/thread/803017 / https://web.archive.org/web/20200607005700/https://www.discogs.com/forum/thread/803017

> I am sorry to have to inform you that we are having to turn off two Discogs features that we have been experimenting with over the last year - the Tracks feature, and the updated Collection feature. The reason for both are technical challenges in making the features stable and fast enough for us to run reliably for everyone. ... However, we have learned a lot from your feedback and usage of both features, and plan to bring them back in improved and stable forms in the not too distant future.

While they hope to bring them back, it's been a year and so this ticket can probably be resolved.

**Comment by murdos** [comment]
@awesomer : thanks for detailed update! 
I'm closing this ticket
