### ISSUE TITLE
Import to MB button not showing for release

### ISSUE THREAD

**Issue by dogebeets** [murdos/musicbrainz-userscripts#30]
http://www.discogs.com/release/4281027

This is the release in question.  Not seeing the import button for this release or another release from the same group.  Not sure why it isn't showing up.  Any thoughts?

**Comment by murdos** [comment]
The button does not appear because the release in unparseable: tracknos "10-31" or "32.1", "32.2" have a very specific meaning that the script can't understand.

**Comment by Freso** [comment]
Couldn't the script be made to understand that though? Recognise that those are the same track in MB terms and separate them with " / "?

**Comment by 96187** [comment]
Are you volunteering? :P

Parsing Discogs track numbers is a difficult problem to solve because Discogs has no proper structure for discs, sides or subtracks, so everything has to be inferred from the track number, but they also don't require standardising the track number syntax, so the same syntax can mean multiple things. There are always going to be more and more edge cases which the code doesn't understand and at some point it becomes more work to add support for those edge cases than it would be for people to just add the release manually.

That said, it seems using a dot for subtracks is mentioned on http://www.discogs.com/help/submission-guidelines-release-trk.html#Position so it seems like it would be a common enough scenario that we would want to support it.

The dash is normally used for separating disc numbers, so the use of it as a range here is unusual and I'm not sure how common that is.

What I *do* think would be a good idea to do would be (instead of just failing to show the import button) to show a message saying the tracklist couldn't be parsed. If it did that, there could also be an option to import the release without the tracklist (i.e. seed all the other data so that the user can just paste the tracklist and fix it manually), or potentially even to import the tracklist with sequential tracks (i.e. not trying to parse the track positions) - although I would expect that to involve some sort of warning/confirmation that the tracklist almost certainly needs fixing.

**Comment by murdos** [comment]
My plan was indeed to add some informative message at some point, but I had not thought about the option consisting of allowing import without the tracklist. 
I like this idea, but I'm not fond of importing the tracklist with sequential tracks because I fear it will lead to bad data added to MusicBrainz.
