### ISSUE TITLE
Discogs import to MB - add import cover art

### ISSUE THREAD

**Issue by ctambour** [murdos/musicbrainz-userscripts#50]
It would be very useful if the Discogs import script was able to also import the cover art from the Discogs release page. When adding lots of releases this takes a considerable amount of time to download and then uploading the cover art.

Has this been discussed before as a possible feature? I have coding skills but wanted to reach out first before trying to add such a feature.

**Comment by zas** [comment]
There is no cover art submission web service in MusicBrainz afaik.
Also i think discogs cover art images aren't great at all, often of low quality and low resolution, often important text can't even been read.
Since an imported release has a link back to discogs release, it isn't much an issue imho.

**Comment by pankkake** [comment]
I could see it as an optional thing, but I don't think it can be done with only an userscript.

There was https://github.com/96187/cover-art-bot but the interface has changed a lot since then (for the better, the reason this script existed was because the interface was horrible when adding a lot of artwork).

In the meantime you can use an extension like DownThemAll to download all the images from Discogs.

**Comment by zas** [comment]
I don't think import user scripts can or should handle cover art upload, especially regarding the lack of stable API.

**Comment by murdos** [comment]
This is something that could be interesting, and very helpful.
Discogs cover art are limited to 600x600, but this is often the best source for old vinyl, cassette, or even CD singles.
Moreover I often encounter Discogs releases that have been imported to MusicBrainz, with only the front cover art added.

I'll try to work on something, but this will probably be a separated script, that would allow uploading cover art one by one with a single click.

**Comment by ldexterldesign** [comment]
~ https://community.metabrainz.org/t/review-fix-cover-art-discogs-release-import/51464

**Comment by Freso** [comment]
> I will endeavour to add cover artwork to both new Discogs and MusicBrainz releases in future, but enhancements to alleviate the MusicBrainz step would be welcomed by me

Keep in mind that the images you download from Discogs are of [lesser quality](https://github.com/murdos/musicbrainz-userscripts/issues/50#issuecomment-111864019) than the ones actually uploaded, so I hope you upload your source images to both Cover Art Archive and Discogs and not first to Discogs and then get the images off of Discogs to add to Cover Art Archive (which is what a userscript doing this would effectively do).

**Comment by ldexterldesign** [comment]
Hey @Freso,

Apologies for delay - been waiting to process my next batch of music

I'm currently sourcing *missing* artwork from iTunes (convenience), which uses 500x500px default dimensions, so the Discogs 600x600px limit isn't really an issue in this instance; but thanks for the tip

I've mulled this over and I'm, waveringly, of the opinion that *any* imported artwork is better than no artwork, even if it's 600x600px. I don't have an issue with <=600x600px imports and if I do I know how I can improve things.

It's my personal opinion that the automation tools should do the best job they can at sourcing the best quality artwork and the manual tools (e.g. https://musicbrainz.org/release/add ) should do the best job at encouraging users to enhance the artwork quality

Hope this is useful and to hear back

Kind regards

**Comment by ldexterldesign** [comment]
Hey @Freso,

Apologies for delay - been waiting to process my next batch of music

I'm currently sourcing missing artwork from iTunes (convenience), which uses 500x500px default dimensions, so the Discogs 600x600px limit isn't really an issue in this instance; but thanks for the tip

I've mulled this over and I'm, waveringly, of the opinion that any imported artwork is better than no artwork, even if it's 600x600px. I don't have an issue with <=600x600px imports and if I do I know how I can improve things.

It's my personal opinion that the automation tools should do the best job they can at sourcing the best quality artwork and the manual tools (e.g. https://musicbrainz.org/release/add ) should do the best job at encouraging users to enhance the artwork quality

Hope this is useful and to hear back

Kind regards

**Comment by ldexterldesign** [comment]
test

**Comment by Freso** [comment]
You should still add your source image straight to CAA instead of uploading the image to Discogs and then getting the image from Discogs to upload to CAA. Even if it's the same resolution, Discogs will apply some changes to the image you download, which will result in it being of lesser quality than the one you uploaded, which is silly.

**Comment by jesus2099** [comment]
FWIW @ldexterldesign, you can find on iTunes images even larger than 1200px: https://github.com/jesus2099/konami-command/blob/master/itunes_FULL-SIZE-COVER-IMAGE-DOWNLOAD-LINK.user.js

**Comment by ldexterldesign** [comment]
Hey @jesus2099,

I didn't know you could access iTunes albums on the web, from a browser

If you can give me a URL to a common album I'll try and get your script working?

Good timing, since I've just stopped using iTunes ~ https://twitter.com/ldexterldesign/status/756197752724459520

Yours hopefully

**Comment by jesus2099** [comment]
I only have browser, I don’t have program like iTunes as I just drag and drop ripped files in audio player(s).
You can find an example in jesus2099/konami-command#193, or, well… many examples from any [web search](https://duckduckgo.com/?q=suede+%22night+thoughts%22+site%3Aitunes.apple.com). :)

**Comment by ldexterldesign** [comment]
@jesus2099 great, I'll have a look into this next time I process a batch of music

Kind thanks

**Comment by eharris** [comment]
I agree this would be a great enhancement to the importer.  While I have nearly all the original media in my collection, I've often gotten rid of the CD cases (and associated cover/back) for space reasons and only have the CD.  So unless I've personally already scanned the covers (which is relatively few of my albums), I tend to use either Amazon or Discogs for the album art, because something is better than nothing.  I've found for the less mainstream releases, Discogs is usually of better quality or is more complete (has back/barcode, media, and sometimes even the booklet scans).

I always try to use the "best" (clearest, highest resolution) images I can so I wouldn't want the cover art import to be fully automatic, but having an easy way to selectively or as a whole import the images from Discogs would be very nice!

**Comment by naught101** [comment]
This would be really useful from Bandcamp, where there's nearly always a decent image available ("original image" link).

**Comment by kellnerd** [comment]
Nowadays you can use [MB: Enhanced Cover Art Uploads](https://github.com/ROpdebee/mb-userscripts#mb-enhanced-cover-art-uploads) which supports Discogs and a few other sites.
