### ISSUE TITLE
Idea: Qobuz import script

### ISSUE THREAD

**Issue by pankkake** [murdos/musicbrainz-userscripts#53]
While it's a fairly generic store, it has some unique releases, and is one of the few offering lossless downloads for those releases.

It has a documented API: https://github.com/Qobuz/api-documentation
Also could be used to provide a link to the full-size cover art.

**Comment by zas** [comment]
I was thinking about doing it... when i will finish with existing scripts... ;)

**Comment by augustjanse** [comment]
I was just about to make this an issue. It would be appreciated if there's time!

**Comment by zas** [comment]
I sent an email to Qobuz to know if it is possible to use their API for such script.
Each application requires an app_id.
It will ease things a lot if we can use it, ie. qobuz pages have localized dates, API provides an unix timestamp for release date.

**Comment by zas** [comment]
I got no answer from Qobuz... i guess we'll end to scrap pages. We'll have to handle i18ned dates...

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/77

Notes:
- Various Artists not handled yet
- use the same app_id as the website, due to the lack of answer of Qobuz API team
- featuring artists are not marked as "feat.", the whole extraction of track artists is a real pain
- release country is based on the current selected "country"
- all qobuz languages should be supported

Please test and report issues

**Comment by zas** [comment]
Merged.
